sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t cwilko/tuya2mqtt:latest .

script:
  - docker run -d --rm cwilko/rpi-stats:latest
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push cwilko/tuya2mqtt